### ISSUE TITLE
IE11 swiping never stops

### ISSUE THREAD

**Issue by Dalirik** [antonreshetov/vue-glide#11]
Hi,
when using IE11, when you swipe using mouse, it never stops. 

It seems to be similar to issue, that glide had months ago. It seems to work with their latest version, which you seem to use as well. [issue](https://github.com/glidejs/glide/issues/248 )

Do you have any idea, what might cause that?

Steps to reproduce:
1) Open https://antonreshetov.github.io/vue-glide/ in IE11
2) Swipe to any direction, using mouse
3) It should be stuck in swiping action

**Comment by antonreshetov** [comment]
Should be fixed with 17cab1d

**Comment by Dalirik** [comment]
It works now. Thank you!
