### ISSUE TITLE
How to use the API? 

### ISSUE THREAD

**Issue by gaglage** [antonreshetov/vue-glide#18]
Its possible to use the API to change properties?

**Comment by antonreshetov** [comment]
Not quite understand the question.
You can change the properties as you like

**Comment by gaglage** [comment]
The idea is use the API Methods to control the Slide Slider.

Documentation explains how to use the event glid:pause and refers to method glide.puse(). I don't know how to use this method in the component. Is it possible? 
Thanks

glide:pause
Called right after stopping instance with **glide.pause()** API method.

**Comment by antonreshetov** [comment]
You can directly call glide.js api methods via reference.
Example - https://codesandbox.io/s/n722774xl

**Comment by gaglage** [comment]
Thanks for your answer and example
