### ISSUE TITLE
Please remove vue package

### ISSUE THREAD

**Issue by 8bu** [antonreshetov/vue-glide#20]
I can't use it with nuxtjs now because my project is using nuxt1.x. That means I'm using vue 2.5.x, but your component file was built on top of vue ^2.5.16. So every time I install your package, vue will be automatically install at 2.6.6 (newest version). That crashed my vue-server-renderer of nuxtjs1.x. 
I tried many ways to override your vue version but nothing work, I have to download your components and run it locally.

**Comment by antonreshetov** [comment]
Hi @8bu 

If you install the vue-glide from npm you already get a build, without vue and does not need npm install. I do not understand the reason for your problem.

Vue in vue-glide is needed as a dependency when developing, but is not needed in using vue-glide as library.

**Comment by 8bu** [comment]
Hi @antonreshetov, thank you for your reply.
I don't understand the situation neither. I was using` vue-glide-js` as dependency but when I'm running build progress, `nuxtjs` response with a version mismatch error about `vue@2.6.6` and `vue-server-renderer@2.5.x`. I used `npm ls vue` to check all `vue` dependencies in project and found your package contains a newer version of `vue`. So I can't run build without removing your package or upgrade `nuxt` to newer version.

**Comment by antonreshetov** [comment]
Unfortunately I don't know how to help, perhaps you should make a fork and make the necessary changes.
