### ISSUE TITLE
Exclude polyfills from build

### ISSUE THREAD

**Issue by Dalirik** [antonreshetov/vue-glide#23]
Hi,
could you exclude the polyfills from the build, It is recommended in official vue [docs](https://cli.vuejs.org/guide/browser-compatibility.html#polyfills-when-building-as-library-or-web-components).
It could reduce the size by quite a bit.

**Comment by antonreshetov** [comment]
Closed because it was fixed in d09270143ab3f44df422a14c0a83b73f3ebe81c3
