### ISSUE TITLE
carousel increasing width of entire page

### ISSUE THREAD

**Issue by dakshshah96** [antonreshetov/vue-glide#24]
First of all, thanks for the work on this incredibly elegant library!

I'm trying to implement a carousel using `vue-glide` on my web app and I keep facing an issue where all the slides are visible at the same time on the page and the page has become horizontally scrollable to accommodate all the slides.

Is this expected behaviour? Here's a reproduction of the issue I'm facing: 

Preview: https://wo196786y5.codesandbox.io/
Code: https://codesandbox.io/s/wo196786y5?fontsize=14

**Comment by antonreshetov** [comment]
Hi @dakshshah96 

1. You not import glide style for correct view of glide
2. The `<template slot="control"></template>` should be into `<vue-glide></vue-glide>`

https://codesandbox.io/s/vy9o768xo5
