### ISSUE TITLE
npm audit found 291 vulnerabilities

### ISSUE THREAD

**Issue by coderdiaz** [antonreshetov/vue-glide#28]
NPM found 291 vulnerabilities in the package.

![image](https://user-images.githubusercontent.com/1901273/55827199-3d055300-5acf-11e9-9abb-a49d0726c31f.png)

**Comment by antonreshetov** [comment]
Run `npm audit fix`

**Comment by antonreshetov** [comment]
Fixed in abd50c6f3386a3ed8a999772b25fc842cdb28233
