### ISSUE TITLE
event glide:slide-click payload undefined

### ISSUE THREAD

**Issue by jeffcunat** [antonreshetov/vue-glide#29]
Since #22, the payload index of the slide-click event is undefined

**Comment by hellomikes** [comment]
Was coming here to say the exact same thing, currently not returning any payload on click

**Comment by jeffcunat** [comment]
I have proposed a PR #30  to fix this issue

**Comment by antonreshetov** [comment]
Closed because it was fixed in 19550b2027c0ccb5aa46b1e2acf8567c2906ecd1
