### ISSUE TITLE
Event glide:slide-click not triggering on cloned carousel slides

### ISSUE THREAD

**Issue by JoakimFFCG** [antonreshetov/vue-glide#32]
The event glide:slide-click does not trigger on cloned carousel slides (those that have the css class glide__slide-clone).

Example: [https://codesandbox.io/s/vue-template-xbffg](https://codesandbox.io/s/vue-template-xbffg)

This appears to be an issue since 1.3.7.
Specifically I think it might have been [this commit](https://github.com/antonreshetov/vue-glide/commit/7529e9cc0a892042bb339b60857b938cc1836e42) that caused the issue.

**Comment by antonreshetov** [comment]
Hi @JoakimFFCG
Thanks for bug. It's fixed in 7620ec4
