### ISSUE TITLE
Peek prop doesn't render propely.

### ISSUE THREAD

**Issue by simonalarie** [antonreshetov/vue-glide#56]
Hello there,

The **peek property** doesn't render before and next viewport's sizes properly unless a browser resize is involved.

Here's my settings:

`<vue-glide 
        :perView = 4
        :peek    = 40
        :rewind  = false
        :bound   = true
        :breakpoints = "{
            992 : {
                perView: 2
            },
            768 : {
                perView: 1
            }
        }"   
    >`

See attached screenshot:

![screensize](https://user-images.githubusercontent.com/38366582/98415913-28db5c00-204c-11eb-958d-a1005fe5f5fd.jpg)

Tested on recent desktop's Edge and Chrome.

Thanks for support.

**Comment by callumflack** [comment]
How did you solve this @simonalarie?
