### ISSUE TITLE
Listening on the index of current  active slide

### ISSUE THREAD

**Issue by sarahxoxo** [antonreshetov/vue-glide#6]
Hi,
I've read the documents, and still don't know how to use events.
Could you give an example about how to listen on the index of current active slide?

**Comment by antonreshetov** [comment]
Hi @sarahxoxo,
The fact that vue-glide provides only those events that are in the glide.js that are prefixed with `glide:`. Glide.js not provide index of active slide.

Currently, vue-glide has a custom event `glide: slide-click` which returns the index of the slide on which the click was made. This part is a further development in which I plan to add slide switching by click.

**Comment by sarahxoxo** [comment]
Hi @antonreshetov ,
Got it. Thanks for your reply.

**Comment by madhurikulkarni** [comment]
@antonreshetov 

> This part is a further development in which I plan to add slide switching by click.

Is there a way to do this currently with the slider. ?

**Comment by madhurikulkarni** [comment]
My solution if it helps someone, using the slide-click
` <vue-glide
          ref="slider"
          @glide:slide-click="moveSlide"
        >`
`moveSlide(index) {
      this.$refs.slider.glide.go(`=${index}`)
    }`

**Comment by Enigama** [comment]
> @antonreshetov
> 
> > This part is a further development in which I plan to add slide switching by click.
> 
> Is there a way to do this currently with the slider. ?

<vue-glide ref="slider" @glide:swipe-end="setDataProducts">
Methods:
setDataProducts(){
this.$refs.slider.glide.index
}
