### ISSUE TITLE
Can't import module

### ISSUE THREAD

**Issue by vcastro45** [antonreshetov/vue-glide#7]
Since I updated to 1.3.0 I cannot import the module using:

`import { Glide, GlideSlide } from 'vue-glide-js'` (same for css files)

The folder structure in node_modules looks like this:
 ##![image](https://user-images.githubusercontent.com/16238958/50631275-05bd5e00-0f44-11e9-94cf-95c886caac38.png)

**Comment by iSWORD** [comment]
I'm having the same problem on 1.3.11.

**Comment by antonreshetov** [comment]
@iSWORD The problem you describe doesn't exist

**Comment by iSWORD** [comment]
I'm sorry, I must have done something wrong, but I'm still unable to use this component because of the above-mentioned issue. I decided to use vue-agile instead. I wouldn't mind helping fix the problem in any possible way, Anton.

**Comment by antonreshetov** [comment]
@iSWORD see proof example - https://codesandbox.io/s/1q1vvvolj3
